name: continuous-integration

on:
  push:
    branches:
      - alpha
      - beta
      - master
  pull_request:
    branches:
      - master

jobs:
  default:
    uses: mixmaxhq/github-workflows/.github/workflows/npm_module.yml@main
    with:
      coverage_threshold: 20
      node_version: 12.22.6
      npm_version: 7.19.0
    secrets: inherit
